package:
  description: "SONATA FW vTC Y1 demo service"
  maintainer: "Manuel Peuster, Paderborn University, manuel.peuster@uni-paderborn.de"
  name: sonata-fw-vtc-service
  vendor: eu.sonata-nfv.package
  version: '0.5'
descriptor_extension: "yml"
version: '0.5'
